# -*- coding: utf-8 -*-
from . import hr_employee
from . import hr_employee_type_config
from . import partner_type
from . import hr_department
#from . import account_move
from . import product
from . import product_sub_type
from . import treatment_room
from . import resource_resource
from . import appointment_resource
from . import daily_encounter
from . import medical_encounter
from . import pending_pos_item
from . import calendar_event
from . import appointment_type
from . import cancellation_reason
from . import medical_encounter_service
from . import res_partner